name: oson_kadastr
description: "Aholi uchun sodda kadastr yordamchisi"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
