name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodlarni yuklash
        uses: actions/checkout@v4

      - name: Java muhitini o'rnatish
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Flutter o'rnatish
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Android karkasini tiklash
        run: |
          mkdir -p android
          flutter create . --org uz.osonkadastr --platforms android --project-name oson_kadastr

      - name: Paketlarni yuklash
        run: flutter pub get

      - name: Logotipni o'rnatish
        run: dart run flutter_launcher_icons

      - name: APK yig'ish
        run: flutter build apk --release

      - name: APK faylni yuklab olishga tayyorlash
        uses: actions/upload-artifact@v4
        with:
          name: oson-kadastr-apk
          path: build/app/outputs/flutter-apk/app-release.apk
